### ISSUE TITLE
CLERK_PUBLISHABLE_KEY is missing

### ISSUE THREAD

**Issue by ghost** [syedahafsa12/photo_gallery#1]
![image](https://github.com/syedahafsa12/photo_gallery/assets/36201799/60b5de11-1f61-41dd-ab7d-6b8551f5a528)

**Comment by syedahafsa12** [comment]
Hi,

Thanks for letting me know that #1 has been closed as completed. I confirm
the receipt of this update.

Best regards,
Syeda Hafsa

**Comment by ghost** [comment]
the issue still need to be solved 😁

**Comment by syedahafsa12** [comment]
just copy the key from your key from .env and paste it into the
environment variable in vercel.

**Comment by ghost** [comment]
The error is in the live deploy link. You need to redeploy the last build from Vercel after updating envs from vercel dashboard.
